# Generated by Django 5.0.1 on 2024-01-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('publisher', models.TextField()),
            ],
        ),
    ]
